cc_library(
        name = "libdembo",
        hdrs = ["dembo.hpp"],
        srcs = ["dembo.cpp"],
        deps = ["//lib:hpp"],
        visibility = ["//visibility:public"],
        include_prefix = "knapsack/ub_dembo/",
)

