cc_library(
        name = "libmartello",
        hdrs = ["martello.hpp"],
        srcs = ["martello.cpp"],
        visibility = ["//visibility:public"],
        deps = ["//lib:cpp", "//ub_dantzig:libdantzig"],
)
