cc_library(
        name = "libsurrogate",
        hdrs = ["surrogate.hpp"],
        srcs = ["surrogate.cpp"],
        visibility = ["//visibility:public"],
        deps = ["//lib:hpp", "//ub_dantzig:libdantzig"],
)
