cc_library(
        name = "dantzig",
        hdrs = ["dantzig.hpp"],
        srcs = ["dantzig.cpp"],
        deps = ["//lib:cpp"],
        visibility = ["//visibility:public"],
        include_prefix = "knapsack/ub_dantzig/",
)

