name: Build

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8"]

    env:
      KNAPSACK_DATA: ${{ github.workspace }}/data/knapsack
      SUBSET_SUM_DATA: ${{ github.workspace }}/data/subset_sum
      MULITPLE_CHOICE_SUBSET_SUM_DATA: ${{ github.workspace }}/data/multiple_choice_subset_sum

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download data
      run: |
        python3 -m pip install gdown
        python3 -u scripts/download_data.py
    - name: Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel
    - name: Run unit tests
      working-directory: build/test
      run: ctest --parallel
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results
    - name: Checkout main branch
      run: |
        git remote set-branches origin '*'
        git fetch --depth 1
        git checkout master
    - name: Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel
    - name: Run tests
      run: python3 -u scripts/run_tests.py test_results_ref
    - name: Process tests
      run: python3 -u ./bazel-packingsolver/external/optimizationtools/scripts/process_tests.py --ref test_results_ref --new test_results
